import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { zodToJsonSchema } from 'zod-to-json-schema'
import { ToxinSchema } from './toxin.zod'

const __dirname = dirname(fileURLToPath(import.meta.url))
const CHECK_ONLY = process.argv.includes('--check')

const typesPath = resolve(__dirname, 'toxin.types.ts')
const jsonSchemaPath = resolve(__dirname, 'toxin.schema.json')

const generatedTypes = `// AUTO-GENERATED by schemas/build-schemas.ts. Do not edit manually.
import { z } from 'zod'
import {
  CategorySchema,
  SeveritySchema,
  SymptomSeveritySchema,
  ToxinChemicalSchema,
  ToxinSchema,
  ToxinSymptomSchema,
  ToxinTreatmentSchema,
} from './toxin.zod'

export type Severity = z.infer<typeof SeveritySchema>
export type Category = z.infer<typeof CategorySchema>
export type SymptomSeverity = z.infer<typeof SymptomSeveritySchema>

export type ToxinSymptom = z.infer<typeof ToxinSymptomSchema>
export type ToxinChemical = z.infer<typeof ToxinChemicalSchema>
export type ToxinTreatment = z.infer<typeof ToxinTreatmentSchema>

export type Toxin = z.infer<typeof ToxinSchema>
`

const schemaObject = zodToJsonSchema(ToxinSchema, {
  name: 'Toxin',
  target: 'jsonSchema7',
  $refStrategy: 'none',
}) as Record<string, unknown>

schemaObject.$schema = 'http://json-schema.org/draft-07/schema#'
const generatedJsonSchema = `${JSON.stringify(schemaObject, null, 2)}\n`

function apply(path: string, next: string): boolean {
  let current = ''
  try {
    current = readFileSync(path, 'utf8')
  } catch {
    current = ''
  }

  if (current === next) return false

  if (CHECK_ONLY) {
    console.error(`[stale] ${path}`)
    return true
  }

  writeFileSync(path, next)
  console.log(`[write] ${path}`)
  return true
}

const changed = [
  apply(typesPath, generatedTypes),
  apply(jsonSchemaPath, generatedJsonSchema),
].some(Boolean)

if (CHECK_ONLY && changed) {
  process.exit(1)
}

if (!changed) {
  console.log(CHECK_ONLY ? 'Schema artifacts are up-to-date.' : 'Schema artifacts already up-to-date.')
}
