import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { zodToJsonSchema } from 'zod-to-json-schema'
import { ToxinDiskSchema, ToxinSchema } from './toxin.zod'

const __dirname = dirname(fileURLToPath(import.meta.url))
const CHECK_ONLY = process.argv.includes('--check')

const typesPath = resolve(__dirname, 'toxin.types.ts')
const jsonSchemaPath = resolve(__dirname, 'toxin.schema.json')
const diskJsonSchemaPath = resolve(__dirname, 'toxin.disk.schema.json')

const generatedTypes = `// AUTO-GENERATED by schemas/build-schemas.ts. Do not edit manually.
import { z } from 'zod'
import {
  CategorySchema,
  SeveritySchema,
  SymptomSeveritySchema,
  ToxinChemicalSchema,
  ToxinDiskSchema,
  ToxinSchema,
  ToxinSymptomSchema,
  ToxinTreatmentSchema,
} from './toxin.zod'

export type Severity = z.infer<typeof SeveritySchema>
export type Category = z.infer<typeof CategorySchema>
export type SymptomSeverity = z.infer<typeof SymptomSeveritySchema>

export type ToxinSymptom = z.infer<typeof ToxinSymptomSchema>
export type ToxinChemical = z.infer<typeof ToxinChemicalSchema>
export type ToxinTreatment = z.infer<typeof ToxinTreatmentSchema>

export type Toxin = z.infer<typeof ToxinSchema>
export type ToxinDisk = z.infer<typeof ToxinDiskSchema>
`

function buildJsonSchema(schema: Parameters<typeof zodToJsonSchema>[0], name: string) {
  const obj = zodToJsonSchema(schema, {
    name,
    target: 'jsonSchema7',
    $refStrategy: 'none',
  }) as Record<string, unknown>
  obj.$schema = 'http://json-schema.org/draft-07/schema#'
  return `${JSON.stringify(obj, null, 2)}\n`
}

const generatedJsonSchema = buildJsonSchema(ToxinSchema, 'Toxin')
const generatedDiskJsonSchema = buildJsonSchema(ToxinDiskSchema, 'ToxinDisk')

function apply(path: string, next: string): boolean {
  let current = ''
  try {
    current = readFileSync(path, 'utf8')
  } catch {
    current = ''
  }

  if (current === next) return false

  if (CHECK_ONLY) {
    console.error(`[stale] ${path}`)
    return true
  }

  writeFileSync(path, next)
  console.log(`[write] ${path}`)
  return true
}

const changed = [
  apply(typesPath, generatedTypes),
  apply(jsonSchemaPath, generatedJsonSchema),
  apply(diskJsonSchemaPath, generatedDiskJsonSchema),
].some(Boolean)

if (CHECK_ONLY && changed) {
  process.exit(1)
}

if (!changed) {
  console.log(CHECK_ONLY ? 'Schema artifacts are up-to-date.' : 'Schema artifacts already up-to-date.')
}
