// AUTO-GENERATED by schemas/build-schemas.ts. Do not edit manually.
import { z } from 'zod'
import {
  CategorySchema,
  SeveritySchema,
  SymptomSeveritySchema,
  ToxinChemicalSchema,
  ToxinSchema,
  ToxinSymptomSchema,
  ToxinTreatmentSchema,
} from './toxin.zod'

export type Severity = z.infer<typeof SeveritySchema>
export type Category = z.infer<typeof CategorySchema>
export type SymptomSeverity = z.infer<typeof SymptomSeveritySchema>

export type ToxinSymptom = z.infer<typeof ToxinSymptomSchema>
export type ToxinChemical = z.infer<typeof ToxinChemicalSchema>
export type ToxinTreatment = z.infer<typeof ToxinTreatmentSchema>

export type Toxin = z.infer<typeof ToxinSchema>
